In [1]:
import numpy as np
import tensorflow as tf

In [2]:
def sigmoid(x):
    return 1/(1 + tf.exp(-x))

In [3]:
class Neuron:
    def __init__(self, weights: tf.Variable, input_val: tf.constant, activation = None):
        self.weights = weights
        self.input_val = input_val

        if activation:
            self.activation = activation
        else:
            self.activation = lambda x: x

    def forward_pass(self):
        return self.activation(tf.reduce_sum(tf.multiply(self.weights, self.input_val)))

    def backprop(self, gradient):
        with tf.GradientTape() as tape:
            y = gradient * self.forward_pass()
        y_w = tape.gradient(y, self.weights)
        return y_w
        

In [4]:
weights = tf.Variable([1.0, 2.0, 1.1])
x = tf.constant([1.0,5.1,3])

N = Neuron(weights, x, sigmoid)

In [5]:
N.forward_pass()

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999995>

In [6]:
sigmoid(tf.reduce_sum(tf.multiply(N.weights, x)))

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999995>

In [7]:
N.backprop(3)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.5130415e-06, 7.7165114e-06, 4.5391243e-06], dtype=float32)>