In [1]:
import numpy as np


In [2]:
class Neuron:
    def __init__(self, n_weights, activation_type='step_function'):
        self.activation_type = activation_type

        self.weights = np.zeros(n_weights)

    def activation(self, X):
        if self.activation_type == 'step_function':
            lin_pred = X @ self.weights
            pred = np.where(lin_pred >= 0, 1, -1)
        return pred

class Perceptron:
    def __init__(self, n_layers=3, n_neurons=1, learning_rate=0.1, max_iter=300):
        self.n_hidden_layers = n_layers - 2
        self.n_neurons = n_neurons
        self._lr = learning_rate
        self.max_iter = max_iter

        self.beta: np.ndarray = None

    def fit(self, X: np.ndarray, y: np.ndarray):
        self.beta = np.zeros(X.shape[1] + 1)
        X = np.concatenate([np.ones((X.shape[0], 1)), X], axis=1)
        N = X.shape[0]

        for _ in range(self.max_iter):
            for i in range(N):
                if y[i] != self.activation(X[i]):
                    self.beta += self._lr * y[i] * X[i]

    def activation(self, X: np.ndarray):
        lin_pred = X @ self.beta
        pred = np.where(lin_pred >= 0, 1, -1)
        return pred

    def predict(self, X: np.ndarray):
        X = np.concatenate([np.ones((X.shape[0], 1)), X], axis=1)
        return self.activation(X)


In [3]:
X = np.array([[1,1], [1,0], [0,1], [0,0]])
y_and = np.array([1, -1, -1, -1])
y_or = np.array([1, 1, 1, -1])
y_xor = np.array([-1, 1, 1, -1])

p = Perceptron(max_iter=100)

p.fit(X, y_and)
print(p.predict(X))

p.fit(X, y_or)
print(p.predict(X))

# 1 neuron perceptron cannot work with non-linearities
p.fit(X, y_xor)
print(p.predict(X))

[ 1 -1 -1 -1]
[ 1  1  1 -1]
[1 1 1 1]
